In [35]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1,2,3,4])
type(s)
s1 = pd.Series([1,2,3,4], index =['a','b','c','d'])
s1

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
data1 = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,777,'jkl']
       ]

data2 = {'ID':[1,2,3,4],
          'std_id':[444,555,666,777],'Dept':['abc','def','ghi','jkl']
        }
df1 = pd.DataFrame(data1, columns=['ID','std_id','Dept'])
df2 = pd.DataFrame(data2, columns=['ID','std_id','Dept'])
display(df2)

   ID  std_id Dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     777  jkl

In [9]:
df2.columns

Index(['ID', 'std_id', 'Dept'], dtype='object')

In [11]:
index = ['row1','row2','row3','row4']
df2.index = index
display(df2)

      ID  std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     777  jkl

In [12]:
df2.dtypes

ID         int64
std_id     int64
Dept      object
dtype: object

In [14]:
df2['Dept'] = df2['Dept'].astype('category')
df2.dtypes

ID           int64
std_id       int64
Dept      category
dtype: object

In [15]:
df2.describe(include='category')

       Dept
count     4
unique    4
top     abc
freq      1

In [18]:
sum_unique = df2['std_id'].unique().sum()
sum_unique

np.int64(2442)

In [19]:
df2.Dept.idxmax()

'row4'

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   std_id  4 non-null      int64
 2   Dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 476.0+ bytes

In [23]:
df2['Dept'].value_counts()

Dept
abc    1
def    1
ghi    1
jkl    1
Name: count, dtype: int64

In [25]:
def duplicate(x):
    return x*2
df2['std_id'].apply(duplicate)

row1     888
row2    1110
row3    1332
row4    1554
Name: std_id, dtype: int64

In [ ]:
df2.iloc[1, 2]

'def'

In [ ]:
df2.iloc[: , 0:2]

      ID  std_id
row1   1     444
row2   2     555
row3   3     666
row4   4     777

In [30]:
df2['new_col'] = df2.std_id + df2.ID
df2

      ID  std_id Dept  new_col
row1   1     444  abc      445
row2   2     555  def      557
row3   3     666  ghi      669
row4   4     777  jkl      781

In [33]:
df2.drop('new_col', axis=1, inplace=True)
df2

      ID  std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     777  jkl

In [34]:
df2.isnull().sum()

ID        0
std_id    0
Dept      0
dtype: int64

In [36]:
data1 = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,np.nan,'jkl']
       ]
df = pd.DataFrame(data1, columns=['ID','std_id','Dept'])
null = df.isnull().sum()
pd.DataFrame(null).T

   ID  std_id  Dept
0   0       1     0

In [38]:
def isNull(df):
    null = df.isnull().sum()
    return pd.DataFrame(null).T

data1 = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,np.nan,'jkl']
       ]
df = pd.DataFrame(data1, columns=['ID','std_id','Dept'])
isNull(df)

   ID  std_id  Dept
0   0       1     0